name: setup selfhost

on:
  push:
    branches:
      - host_setup
  pull_request:
    branches:
      - host_setup

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        run: |
          sudo apt update
          sudo apt install -y unzip curl git
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt install -y nodejs
          
      - name: Verify installations
        run: |
          node -v
          npm -v
          unzip -v
          git --version
          curl --version
