name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version:  ">=1.6 <2.0"  

      - name: Terraform Init
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_user: ${{ secrets.PM_USER }}
          TF_VAR_pm_password: ${{ secrets.PM_PASSWORD }}
        working-directory: Terraform
        run: terraform init

      - name: Ignore existing VMs
        working-directory: Terraform
        run: |
          for vm in github another_vm; do
            if terraform state list | grep -q "module.proxmox_vms\[\"$vm\"\].proxmox_vm_qemu.vm"; then
              terraform state rm -lock=false "module.proxmox_vms[\"$vm\"].proxmox_vm_qemu.vm"
            fi
          done

        
      - name: Terraform Plan
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_user: ${{ secrets.PM_USER }}
          TF_VAR_pm_password: ${{ secrets.PM_PASSWORD }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        working-directory: Terraform
        run: terraform plan


      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_user: ${{ secrets.PM_USER }}
          TF_VAR_pm_password: ${{ secrets.PM_PASSWORD }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        working-directory: Terraform
        run: terraform apply -refresh=false -auto-approve

